### ISSUE TITLE
Github actionsでzshコマンドが使えない

### ISSUE THREAD

**Issue by kiyocy24** [kiyocy24/dotfiles#4]

**Comment by k-jun** [comment]
ちゃんとmagic commentで解消したようで良かったよかった。

**Comment by kiyocy24** [comment]
残念ながら解決しておりませぬ

**Comment by kiyocy24** [comment]
`          curl -fsSL https://raw.githubusercontent.com/kiyocy24/dotfiles/master/install.sh | zsh
`

actionsのshellにzshを指定した

**Comment by k-jun** [comment]
つら。
